# Generated by Django 5.1.5 on 2025-02-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_alter_profiles_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiles",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="files/profile_images/default.jpg",
                null=True,
                upload_to="static/files/profile_images/",
            ),
        ),
    ]
