# Generated by Django 5.1.5 on 2025-03-04 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0004_alter_profiles_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiles",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_auth.contact",
            ),
        ),
    ]
