# Generated by Django 5.1.5 on 2025-03-04 12:28

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ar_name", models.CharField(max_length=250, unique=True)),
                ("en_name", models.CharField(blank=True, max_length=250, null=True)),
                ("code", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.CreateModel(
            name="ArduinoReader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique RFID code scanned by the Arduino",
                        max_length=15,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when the RFID entry was created",
                    ),
                ),
                (
                    "queried",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the RFID entry has been processed",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional ID of the Arduino device that sent this data",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        help_text="Processing status of the RFID data",
                        max_length=10,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arduino RFID Entry",
                "verbose_name_plural": "Arduino RFID Entries",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="EstablishmentRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ar_name", models.CharField(max_length=250, unique=True)),
                ("en_name", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "verbose_name": "Establishment Role",
                "verbose_name_plural": "Establishment Roles",
            },
        ),
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ar_name", models.CharField(max_length=250, unique=True)),
                ("en_name", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "verbose_name": "Main Category",
                "verbose_name_plural": "Main Categories",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ar_name", models.CharField(max_length=250, unique=True)),
                ("en_name", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
            },
        ),
        migrations.CreateModel(
            name="Establishment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rifd", models.CharField(max_length=100, unique=True)),
                ("establishment_name", models.CharField(max_length=200)),
                ("owner_name", models.CharField(max_length=200)),
                ("owner_number", models.CharField(max_length=50)),
                ("director_name", models.CharField(max_length=200)),
                ("director_number", models.CharField(max_length=50)),
                ("representative_name", models.CharField(max_length=200)),
                ("representative_number", models.CharField(max_length=200)),
                ("box_O_P", models.BigIntegerField()),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone_number", models.CharField(max_length=50)),
                ("municipality_name", models.CharField(max_length=200)),
                ("region_number", models.CharField(max_length=50)),
                ("street_number", models.BigIntegerField()),
                ("street_name", models.CharField(max_length=200)),
                ("building_number", models.BigIntegerField()),
                ("block_number", models.BigIntegerField()),
                ("block_name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licesnsing.activity",
                    ),
                ),
                (
                    "main_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licesnsing.maincategory",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licesnsing.subcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstablishmentRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issuance_date",
                    models.DateField(
                        help_text="The date when the car license was issued."
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        help_text="The date when the car license expires."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the registration record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the registration record was last updated.",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        help_text="The establishment issuing this car license registration.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registers",
                        to="licesnsing.establishment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Establishment Register",
                "verbose_name_plural": "Establishment Registers",
                "ordering": ["-issuance_date"],
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_number",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Register Number"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Inspection Notes"
                    ),
                ),
                ("latitude", models.IntegerField(verbose_name="Latitude")),
                ("longitude", models.IntegerField(verbose_name="Longitude")),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Accepted"), (False, "Refused")],
                        default=False,
                        verbose_name="Inspection Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date and Time of Inspection"
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "register_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="C:\\Users\\HASSAN\\PycharmProjects\\LTLMS\\static"
                        ),
                        upload_to="inspections/register_photos/",
                        verbose_name="Register Photo",
                    ),
                ),
                (
                    "license_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="C:\\Users\\HASSAN\\PycharmProjects\\LTLMS\\static"
                        ),
                        upload_to="inspections/license_photos/",
                        verbose_name="License Photo",
                    ),
                ),
                (
                    "establishment_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="C:\\Users\\HASSAN\\PycharmProjects\\LTLMS\\static"
                        ),
                        upload_to="inspections/establishment_photos/",
                        verbose_name="Establishment Photo",
                    ),
                ),
                (
                    "cars_building_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="C:\\Users\\HASSAN\\PycharmProjects\\LTLMS\\static"
                        ),
                        upload_to="inspections/cars_building_photos/",
                        verbose_name="Cars Building Photo",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inspector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Assigned At"),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Due Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Assignment Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Assignment Notes"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_assignments",
                        to="licesnsing.establishment",
                        verbose_name="Establishment",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inspector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Assignment",
                "verbose_name_plural": "Inspection Assignments",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="EstablishmentLicence",
            fields=[
                (
                    "number",
                    models.AutoField(
                        help_text="Auto-incrementing primary key representing the licence number.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(
                        help_text="The date when the licence was created."
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(help_text="The date when the licence expires."),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the licence record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the licence record was last updated.",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        help_text="Reference to the activity associated with this licence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licesnsing.activity",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        help_text="Reference to the registration record associated with this licence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licences",
                        to="licesnsing.establishmentregister",
                    ),
                ),
                (
                    "main_category",
                    models.ForeignKey(
                        help_text="Reference to the main category associated with this licence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licesnsing.maincategory",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        help_text="Reference to the sub category associated with this licence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licesnsing.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Establishment Licence",
                "verbose_name_plural": "Establishment Licences",
                "ordering": ["-creation_date"],
            },
        ),
    ]
