# Generated by Django 5.1.5 on 2025-03-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licesnsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='latitude',
            field=models.CharField(max_length=20, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='longitude',
            field=models.CharField(max_length=20, verbose_name='Longitude'),
        ),
    ]
