# Generated by Django 5.1.5 on 2025-02-12 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licesnsing", "0003_alter_arduinoreader_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arduinoreader",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Timestamp when the RFID entry was created",
            ),
        ),
    ]
