# Generated by Django 5.1.5 on 2025-02-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licesnsing", "0004_alter_arduinoreader_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inspection",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
