# Generated by Django 5.1.5 on 2025-02-19 08:26

import django.db.models.deletion
import licesnsing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licesnsing", "0005_inspection_archived_at_inspection_is_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspection",
            name="cars_building_photo",
        ),
        migrations.RemoveField(
            model_name="inspection",
            name="establishment_photo",
        ),
        migrations.RemoveField(
            model_name="inspection",
            name="license_photo",
        ),
        migrations.RemoveField(
            model_name="inspection",
            name="register_photo",
        ),
        migrations.CreateModel(
            name="InspectionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("register_photo", "Register Photo"),
                            ("license_photo", "License Photo"),
                            ("establishment_photo", "Establishment Photo"),
                            ("cars_building_photo", "Cars Building Photo"),
                        ],
                        max_length=50,
                        verbose_name="Media Type",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=licesnsing.models.inspection_media_upload_to,
                        verbose_name="Image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded at"),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="licesnsing.inspection",
                        verbose_name="Inspection",
                    ),
                ),
            ],
        ),
    ]
