# Generated by Django 5.1.5 on 2025-03-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licesnsing", "0008_inspectionassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="cars_building_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="inspections/cars_building_photos/",
                verbose_name="Cars Building Photo",
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="establishment_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="inspections/establishment_photos/",
                verbose_name="Establishment Photo",
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="license_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="inspections/license_photos/",
                verbose_name="License Photo",
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="register_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="inspections/register_photos/",
                verbose_name="Register Photo",
            ),
        ),
        migrations.DeleteModel(
            name="InspectionMedia",
        ),
    ]
