# Generated by Django 5.1.5 on 2025-03-04 07:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licesnsing", "0009_inspection_cars_building_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="cars_building_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="C:\\Users\\HASSAN\\PycharmProjects\\LTLMS\\static"
                ),
                upload_to="inspections/cars_building_photos/",
                verbose_name="Cars Building Photo",
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="establishment_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="C:\\Users\\HASSAN\\PycharmProjects\\LTLMS\\static"
                ),
                upload_to="inspections/establishment_photos/",
                verbose_name="Establishment Photo",
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="license_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="C:\\Users\\HASSAN\\PycharmProjects\\LTLMS\\static"
                ),
                upload_to="inspections/license_photos/",
                verbose_name="License Photo",
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="register_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="C:\\Users\\HASSAN\\PycharmProjects\\LTLMS\\static"
                ),
                upload_to="inspections/register_photos/",
                verbose_name="Register Photo",
            ),
        ),
    ]
